package com.trendstream.model;

import java.io.Serializable;
import java.util.List;

/**
 * Fraud Alert
 * Represents a fraud detection alert generated by the FraudDetector.
 */
public class FraudAlert implements Serializable {
    
    private static final long serialVersionUID = 1L;
    
    public enum AlertType {
        RAPID_ORDERS,
        LOCATION_ANOMALY,
        HIGH_VALUE_FIRST_ORDER,
        SUSPICIOUS_PATTERN
    }
    
    private String alertId;
    private String userId;
    private String orderId;
    private AlertType alertType;
    private Double riskScore;
    private String description;
    private Long detectedAt;
    private List<String> relatedEvents;
    
    public FraudAlert() {}
    
    public FraudAlert(String alertId, String userId, AlertType alertType, Double riskScore, String description) {
        this.alertId = alertId;
        this.userId = userId;
        this.alertType = alertType;
        this.riskScore = riskScore;
        this.description = description;
        this.detectedAt = System.currentTimeMillis();
    }
    
    // Getters and Setters
    public String getAlertId() { return alertId; }
    public void setAlertId(String alertId) { this.alertId = alertId; }
    
    public String getUserId() { return userId; }
    public void setUserId(String userId) { this.userId = userId; }
    
    public String getOrderId() { return orderId; }
    public void setOrderId(String orderId) { this.orderId = orderId; }
    
    public AlertType getAlertType() { return alertType; }
    public void setAlertType(AlertType alertType) { this.alertType = alertType; }
    
    public Double getRiskScore() { return riskScore; }
    public void setRiskScore(Double riskScore) { this.riskScore = riskScore; }
    
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
    
    public Long getDetectedAt() { return detectedAt; }
    public void setDetectedAt(Long detectedAt) { this.detectedAt = detectedAt; }
    
    public List<String> getRelatedEvents() { return relatedEvents; }
    public void setRelatedEvents(List<String> relatedEvents) { this.relatedEvents = relatedEvents; }
    
    @Override
    public String toString() {
        return "FraudAlert{" +
                "alertId='" + alertId + '\'' +
                ", userId='" + userId + '\'' +
                ", alertType=" + alertType +
                ", riskScore=" + riskScore +
                '}';
    }
}
